import { ListSessionType } from '../types/myTypes';

export const sessionListConst: ListSessionType[] = [

    {
        'name': 'Yoga',
        'date': '2024-01-15T08:00:00Z',
        'type': 'group',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-01-15T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-01-15T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Calisthenics',
        'date': '2024-01-15T07:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Meditation',
        'date': '2024-01-15T09:00:00Z',
        'type': 'personal',
        'category': 'health',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-01-15T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Workout',
        'date': '2024-01-16T12:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-01-16T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-01-16T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Yoga',
        'date': '2024-01-17T08:00:00Z',
        'type': 'group',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-01-17T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-01-17T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-01-18T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Calisthenics',
        'date': '2024-01-18T07:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Meditation',
        'date': '2024-01-18T09:00:00Z',
        'type': 'personal',
        'category': 'health',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-01-19T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Workout',
        'date': '2024-01-19T12:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-01-19T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-01-19T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Yoga',
        'date': '2024-01-20T08:00:00Z',
        'type': 'group',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-01-20T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-01-20T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-01-20T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Calisthenics',
        'date': '2024-01-21T07:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },


];

export const numToDat: { [key: number]: string } = {
    1: 'M',
    2: 'T',
    3: 'W',
    4: 'Th',
    5: 'F',
    6: 'S',
    0: 'Su',
};
