import { ListSessionType } from '../types/myTypes';

export const sessionListConst: ListSessionType[] = [

    {
        'name': 'Yoga',
        'date': '2024-01-15T08:00:00Z',
        'type': 'group',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-01-15T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-01-15T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Calisthenics',
        'date': '2024-01-15T07:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Meditation',
        'date': '2024-01-15T09:00:00Z',
        'type': 'personal',
        'category': 'health',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-01-15T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Workout',
        'date': '2024-01-16T12:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-01-17T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-01-18T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Yoga',
        'date': '2024-01-19T08:00:00Z',
        'type': 'group',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-01-20T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-01-21T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-01-22T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Calisthenics',
        'date': '2024-01-23T07:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Meditation',
        'date': '2024-01-24T09:00:00Z',
        'type': 'personal',
        'category': 'health',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-01-25T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Workout',
        'date': '2024-01-26T12:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-01-27T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-01-28T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Yoga',
        'date': '2024-01-29T08:00:00Z',
        'type': 'group',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-01-30T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-01-31T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-02-01T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Calisthenics',
        'date': '2024-02-02T07:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Meditation',
        'date': '2024-02-03T09:00:00Z',
        'type': 'personal',
        'category': 'health',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-02-04T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Workout',
        'date': '2024-02-05T12:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-02-06T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-02-07T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Yoga',
        'date': '2024-02-08T08:00:00Z',
        'type': 'group',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-02-09T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-02-10T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-02-11T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Calisthenics',
        'date': '2024-02-12T07:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Meditation',
        'date': '2024-02-13T09:00:00Z',
        'type': 'personal',
        'category': 'health',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-02-15T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Workout',
        'date': '2024-02-15T12:00:00Z',
        'type': 'group',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-02-16T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Strength Training',
        'date': '2024-02-17T10:00:00Z',
        'type': 'personal',
        'category': 'strength',
        'isBooked': false,
    },
    {
        'name': 'Yoga',
        'date': '2024-02-18T08:00:00Z',
        'type': 'group',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Burn',
        'date': '2024-02-19T16:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },
    {
        'name': 'Dance Fitness',
        'date': '2024-02-20T18:00:00Z',
        'type': 'webinar',
        'category': 'mobility',
        'isBooked': false,
    },


];

export const numToDat: { [key: number]: string } = {
    1: 'M',
    2: 'T',
    3: 'W',
    4: 'Th',
    5: 'F',
    6: 'S',
    0: 'Su',
};
